./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/q03.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/q04.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/q05.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/q06.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/q07.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/q08.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/q09.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/q10.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcarrosb100.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcarrosb50.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcarrosb500.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol1-trj12.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol1-trj13.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol1-trj14.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol1-trj15.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10-trj2_engavetados-2.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10-trj2_engavetados-3.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10-trj2_engavetados-4.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10-trj2_engavetados-5.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol100_2.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol100_3.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol100_4.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol100_5.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol100_removidos-eng-1_engavetados-2.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol100_removidos-eng-1_engavetados-3.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol100_removidos-eng-1_engavetados-4.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol100_removidos-eng-1_engavetados-5.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10_removidos-1_engavetados-2.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10_removidos-1_engavetados-3.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10_removidos-1_engavetados-4.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10_removidos-1_engavetados-5.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10_removidos-3_engavetados-4.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10_removidos-3_engavetados-5.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10_removidos-eng-1_engavetados-2.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10_removidos-eng-1_engavetados-3.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10_removidos-eng-1_engavetados-4.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol10_removidos-eng-1_engavetados-5.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol1_2.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol1_3.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol1_4.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/qcol1_5.qry
./siguel -e ./test -o ./out -f c1.geo -pm c1.pm -ec c1.ec -v c1-v.via -q c1/todos.qry
